spring:
  application:
    name: Devices
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/devices
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: sqlveo@gmail.com
    password: ybmo etqy gxjf amzd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true